<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Helper.fs" />
    <Compile Include="CollectionTest.fs" />
    <Compile Include="UnitTest.fs" />
    <Compile Include="OptionTest.fs" />
    <Compile Include="RecordTest.fs" />
    <Compile Include="DUTest.fs" />
    <Compile Include="StructDUTest.fs" />
    <Compile Include="AsyncTest.fs" />
    <Compile Include="ClassTest.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="FSharp.Core" Version="9.0.100" />
    <ProjectReference Include="..\..\src\MessagePack.FSharpExtensions\MessagePack.FSharpExtensions.csproj" />
  </ItemGroup>
</Project>
